import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import { UIProvider } from "./providers";
import { AppDataProvider } from "@/context/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Oguz Durmaz - Senior Frontend Engineer Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UIProvider>
          <AppDataProvider>{children}</AppDataProvider>
        </UIProvider>
      </body>
    </html>
  );
}
